name: test-stack-sundar-guntnur-rur
description: This is a stack to create a stack.
branding:
  icon: layers
  color: blue

configs:
  repo-metadata:
    parameters:
      topics:
        - rails
        - blue
